### ISSUE TITLE
How to actually setup?

### ISSUE THREAD

**Issue by LSleutsky** [SmiteshP/nvim-gps#47]
This plugin looks amazing, but I am not understanding how to actually set this up? In which file am I supposed to call

```viml
require("nvim-gps").setup()
```

My SpaceVim config is all in `.vim` files / Vimscript. I am not really familiar with Lua. Where am I supposed to add the initial `setup` call to get this plugin to work? Then do I add the below function just to my `init.vim` file?

```viml
func! NvimGps() abort
  return luaeval("require'nvim-gps'.is_available()") ?
           \ luaeval("require'nvim-gps'.get_location()") : ''
endf
```

Sorry. I'm new to all this, and new to Vim, and the README does not really tell me much. Thanks!

**Comment by Lazytangent** [comment]
I'm not a SpaceVim guy, but I got it working with these changes to the `~/.SpaceVim.d/init.toml` file and a new `~/.SpaceVim.d/after/plugin/plugins.vim` file. The second file just needs to be a file that gets read by the Vim runtimepath.

In the `init.toml` file, I added
```toml
[options]
    # Didn't touch the original config, just added one line at the bottom of this section
    statusline_right_sections = ['cursorpos', 'percentage', 'gps']
    # I add the `gps` section in the `plugins.vim` file

# Other stuff I didn't touch

# Towards the bottom, I added two `custom_plugins` sections
[[custom_plugins]]
    repo = 'nvim-treesitter/nvim-treesitter'

[[custom_plugins]]
    repo = 'SmiteshP/nvim-gps'
```

Then in the `plugins.vim` file, I added

```vim
lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    -- Here's where you'd put whatever languages you wanted the GPS plugin to work on
  },
  -- Toggle on whichever modules you want, as well
}

# Call the setup function for the plugin
require'nvim-gps'.setup()
<<<

" Here's where I put the function from the README
func! NvimGps() abort
  return luaeval("require'nvim-gps'.is_available()") ?
           \ luaeval("require'nvim-gps'.get_location()") : ''
endf
```

I got it to work in a JavaScript file after setting it up and letting it install the two plugins. With this setup, it should appear in the bottom right of the statusline.
